Word: 'Banana'
# Hello this is a comment!
Number: 52
Boolean: true
String-list:
  - 'Value1'
  - 'Value2'
  - 'Value3'
Test:
  Test1:
  Test2:
    Test2.1:
      # Test.Test2.Test2.1
  Test3:
    #Test.Test3